#!/usr/bin/env bash
set -o errexit
# set -o nounset
set -o pipefail

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
CUR_DIR=$(pwd)

CERTS_DIR=$BASE_DIR/certificates

if [ ! -d $CERTS_DIR ]; then
	mkdir -p $CERTS_DIR
fi

cd $CERTS_DIR

if [[ -d out && "$1" == "replace" ]]; then
  rm -Rf out
fi

ORG="Local Development Corp. LLC. Inc."
ORG_UNIT="Local Development"
COMMON_NAME="host.local"
DOMAIN="*.host.local,localhost,0.0.0.0,127.0.0.1"
EXPIRES="2 years"
COUNTRY="US"
PROVINCE="California" # state
LOCALITY="San Diego" # city

if [[ ! $(which certstrap) ]]; then
	echo ""
	echo "✖ certstrap not found."
	echo 
	echo "  https://github.com/square/certstrap"
  echo 
  echo "  Unable to find certstrap to generate self-signed local development certificates."
  echo 
  echo "Will attempt to install..."
  
  brew install certstrap
  
  if [[ ! $(which certstrap) ]]; then
    echo 
    echo "  Install did not succeed, you will need to install manually."
    echo 
    echo "  Please visit for more info:"
    echo "  https://github.com/square/certstrap"
    echo 
    exit 1
  fi
	
fi

echo "=== init cert authority ==="
certstrap init --common-name "${ORG} CA" \
  --expires "${EXPIRES}" \
  --organization "${ORG}" \
  --organizational-unit "${ORG_UNIT}" \
  --country "${COUNTRY}" \
  --province "${PROVINCE}" \
  --locality "${LOCALITY}" \
  --passphrase ""
  # --depot-path "$BASE_DIR/certificates"

echo "=== request certs ==="
certstrap request-cert --common-name "${COMMON_NAME}" \
  --ip 127.0.0.1 \
  --domain ${DOMAIN} \
  --organization "${ORG}" \
  --organizational-unit "${ORG_UNIT}" \
  --country "${COUNTRY}" \
  --province "${PROVINCE}" \
  --locality "${LOCALITY}" \
  --passphrase ""

echo "=== sign certs ==="
certstrap sign "${COMMON_NAME}" \
  --CA "${ORG} CA" \
  --expires "${EXPIRES}" \
  --passphrase ""
  # --intermediate
echo "=== done ==="

cd $CUR_DIR

# mv $BASE_DIR/out $BASE_DIR/certificates

CERT=$(cat $BASE_DIR/certificates/out/${COMMON_NAME}.crt)
KEY=$(cat $BASE_DIR/certificates/out/${COMMON_NAME}.key)
ROOTCA=$(cat $BASE_DIR/certificates/out/${ORG// /_}_CA.crt)

certsgo=$(cat <<EOF
package insecure

// Auto-Generated by create_certs.sh 
const (
    // Public Cert Value
    Cert = \`${CERT}\`
    
    // Private Key Value
    Key = \`${KEY}\`
    
    // Root CA Value
    RootCA = \`${ROOTCA}\`
)

EOF
)

echo "$certsgo" > $BASE_DIR/insecure/certs.go

cd $CUR_DIR